=== atcult/mod-cataloging/raml/schemas/subfieldsTag.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title": "Subfields tag Schema",
  "type": "object",
  "properties": {
    "category": {
      "type": "integer"
    },
    "tag": {
      "type": "string"
    },
    "defaultSubfield": {
      "type": "string"
    },
    "subfields": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repeatable": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false
}

=== atcult/mod-cataloging/raml/examples/subfieldsTag.json
{
    "category": 4,
    "tag": "600",
    "defaultSubfield": "a",
    "subfields": [
        "a",
        "q",
        "b",
        "c",
        "d",
        "e",
        "t",
        "n",
        "p",
        "l",
        "k",
        "f",
        "g",
        "h",
        "s",
        "m",
        "o",
        "r",
        "u",
        "x",
        "y",
        "z",
        "v",
        "0",
        "2",
        "3",
        "4",
        "6",
        "j"
    ],
    "repeatable": [
        "c",
        "e",
        "n",
        "p",
        "k",
        "m",
        "x",
        "y",
        "z",
        "v",
        "0",
        "4",
        "j"
    ]
}
